# Generated by Django 5.2.4 on 2025-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
