# Generated by Django 5.2.7 on 2025-10-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='PermitApplication',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='rating',
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.TextField(help_text='Comma-separated tags (e.g., Trekking, Cultural, Adventure)'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
