# Generated by Django 5.2.7 on 2025-10-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_category_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('tags', models.TextField(help_text='Comma-separated tags (e.g., Electronics, Apparel)')),
                ('category', models.CharField(default='general', max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
